### ISSUE TITLE
UnicodeEncodeError: Games with unicode symbol cause an exception.

### ISSUE THREAD

**Issue by ClackyClacky** [ChriZ982/gog-galaxy-2.0-stats-exporter#4]
Hi Chris,

Great work so far! I was looking to do something like this and am glad someone further along the programming journey picked up the project. I didn't have any idea where the GOG galaxy data was being stored. Just have a little issue on my end with certain games (This traceback is from Assetto Corsa Competitionze on Steam, but I've a feeling games with ™ or ®in the title would also throw this error.

Traceback (most recent call last):
  File "C:/Users/daleh/PycharmProjects/gogstats/src/gog_stats_exporter.py", line 50, in <module>
    writer.writerow(game)
  File "C:\Users\daleh\AppData\Local\Programs\Python\Python37\lib\csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Users\daleh\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2962-2963: character maps to <undefined>

I changed the "with open" line to the following and it worked perfectly. I'm extremely new to python so there might be a perfectly valid reason why this doesn't work out of the box but I just said I'd let you know.

Cheers and I wish you all the best,
Clackyclacky 
```python
    with open(args.output, 'w',encoding='utf8') as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for game in games.values():
            writer.writerow(game)
```

**Comment by ChriZ982** [comment]
Hi @ClackyClacky,
thanks for your feedback! I'm glad you like the project! Please let me know if you have any suggestions to improve it.

I tested the exporter in the Ubuntu WSL. Thats why the encoding was utf8 by default for me. I think the default Windows encoding is iso-8859-1. I will include your suggested change in the next commit. Thanks for pointing me to the issue!

As you propably noticed, this project is in the early stage. I'm even thinking about rewriting the csv exporter in golang to have increased performance and an executable for windows users.

Best regards,
Chris
