### ISSUE TITLE
Seems like OwnedGames has been removed?

### ISSUE THREAD

**Issue by ClackyClacky** [ChriZ982/gog-galaxy-2.0-stats-exporter#6]
Hi Chris,

It's me again, hope you are safe whereever you are.

I've come across a new issue which is more than likley a result of the Gog Galaxy update.

Scanning the db with DB browser led me to the conclusion that the OwnedGames table is gone.

I've seemed to fix the issues by using a different table to do the merge and have gotten successful csv output but I feel like some bigger changes would have to happen on the Dash side to fix this issue.

```SQL
SELECT LibraryReleases.releaseKey,GamePieceTypes.type, GamePieces.userid, GamePieces.value from LibraryReleases
LEFT JOIN GamePieces ON LibraryReleases.releaseKey=GamePieces.ReleaseKey
LEFT JOIN GamePieceTypes ON GamePieces.gamePieceTypeId = GamePieceTypes.id
LEFT JOIN GameTimes ON GameTimes.releaseKey = GamePieces.releaseKey
```

Hope you are well,

Dale

**Comment by ChriZ982** [comment]
Hi Dale :grinning:

Thanks for letting me know!
Pretty sure it was renamed to `LibraryReleases` as you already mentioned.
I will implement your change in my next release.

Best regards,
Chris

**Comment by ChriZ982** [comment]
Moved to https://gitlab.com/ChriZ98/gog-galaxy-2-0-stats-exporter/-/issues/6
